// Generated by init-tenant-repo.mjs
export const TENANT_CONFIG = {
  id: 'valor-plus',
  name: 'Valor Plus SISAN',
  type: 'frontend',
  repos: {
    backend: '/home/gooderp-dev/framework-sdd/develop/valor-plus/backend/valor-plus-sisan-backend',
    frontend: '/home/gooderp-dev/framework-sdd',
    framework: '/home/gooderp-dev/framework-sdd/develop/framework-sdd'
  },
  paths: {
    spec: 'openspec/valor-plus/_changes',
    src: 'src/app/features',
    tests: 'src/**/*.spec.ts',
    e2e: 'e2e/**/*.spec.ts'
  },
  cache: {
    enabled: true,
    path: '.cache/tenant-valor-plus',
    ttl: 3600
  }
};
